### ISSUE TITLE
More of a suggestion then a issue

### ISSUE THREAD

**Issue by troyofathens** [andrewkarch/OverwatchCounters#1]
I think it would be more convenient to the user if you put the teams on the left and right (enemy team on one side recommended on the other) and display it vertically as a way to prevent the need to scroll.
![ow suggestion](https://cloud.githubusercontent.com/assets/21369785/19844252/22b4e3c6-9f01-11e6-81c7-222e2b0b1c8f.png)
here's an example to go off of.  Sorry if I'm insulting your work because it truly is great!

**Comment by andrewkarch** [comment]
I think it looks great!  I'll experiment with it tomorrow
