### ISSUE TITLE
[Feature request] My team is...

### ISSUE THREAD

**Issue by hodgep** [andrewkarch/OverwatchCounters#6]
Ability to input the heros that have been selected for your team and receive recommendations on which heros would be best for you to play

**Comment by ClausWiingreen** [comment]
That will probably first be relevant when synergies/combos are reimplemented

**Comment by andrewkarch** [comment]
There is a soft form of this. The heroes are order from best (left) to not as good (right). Pick the hero closest to the left you can.

It has been requested to add the ability to lock heroes to your team.  That functionality is coming.

**Comment by hodgep** [comment]
Thankyou! Your work is very much appriciated

**Comment by andrewkarch** [comment]
Ability to lock heroes will be in the next update coming today or tomorrow.

**Comment by andrewkarch** [comment]
Implemented
