### ISSUE TITLE
Is this still up to date ?

### ISSUE THREAD

**Issue by DeastinY** [andrewkarch/OverwatchCounters#8]

**Comment by andrewkarch** [comment]
I am working to get better data and a mobile port is 90% done.

I've had some major life changes (Moving, new job, health issues, etc.)

If you can find a better source of data please let me know. I've emailed owfire.com and asked if I can scrape their website for data.

**Comment by DeastinY** [comment]
Hey, great to hear this is still alive !
I love the original work :) I adopted the orphaned [OverwatchWatcher](https://github.com/DeastinY/OverwatchWatcher) and have quite some issues getting proper data as well. AFAIK Blizzard is working on some API, but no details yet.
What would you say about some collaboration ? The OverwatchWatcher can take screenshots and guess the characters so you do not need to manually enter them. If you provide an API I could maybe redirect people to your website !:)

**Comment by andrewkarch** [comment]
Sure, email me at andrewkarchdev@gmail.com
